export const CHANGE_SEARCHFIELD = 'CHANGE_SEARCHFIELD';

export const ROBOT_REQUEST_ISPENDING = 'ROBOT_REQUEST_ISPENDING';

export const ROBOT_REQUEST_SUCCESS = 'ROBOT_REQUEST_SUCCESS';

export const ROBOT_REQUEST_ERROR = 'ROBOT_REQUEST_ERROR'; 
